CURSO = """CREATE TABLE [Curso] ( 
CODCURS INT, 
NOMECURS VARCHAR(45), 
ESTRUTURACURS VARCHAR(45), 
MODALIDADECURS VARCHAR(45), 
CAMPUSCURS VARCHAR(3), 
PMINCURS INT, 
PMAXCURS INT, 
PRIMARY KEY (CODCURS) 
);
"""

ALUNO = """CREATE TABLE [Aluno] ( 
CPFALUNO VARCHAR(45), 
NOMEALUNO VARCHAR(45), 
PRIMARY KEY (CPFALUNO) 
);
"""

SEGURADORA = """CREATE TABLE [Seguradora] ( 
CNPJSEGURADORA VARCHAR(45), 
NOMESEGURADORA VARCHAR(45), 
PRIMARY KEY (CNPJSEGURADORA) 
);"""

ORIENTADOR = """CREATE TABLE [Orientador] ( 
ORIENUMMATRICULA INT, 
ORIENOME VARCHAR(45), 
PRIMARY KEY (ORIENUMMATRICULA) 
);
"""

SUPERVISOR = """CREATE TABLE [Supervisor] ( 
CPFSUPERVISOR VARCHAR(45), 
NOMESUPERVISOR VARCHAR(45), 
EMAILSUPERVISOR VARCHAR(45), 
PRIMARY KEY (CPFSUPERVISOR) 
);
"""

CONCEDENTE = """CREATE TABLE [Concedente] ( 
CNPJCONCEDENTE VARCHAR(45), 
NOMECONCEDENTE  VARCHAR(45), 
ENDCONCEDENTE VARCHAR(45), 
BAIRROCONCEDENTE VARCHAR(45), 
CIDADECONCEDENTE VARCHAR(45), 
PRIMARY KEY (CNPJCONCEDENTE) 
);
"""

INSCRITO = """CREATE TABLE [Inscrito] ( 
INSCMATRICULA int, 
CODCURS INT, 
CPFALUNO  VARCHAR(45),
INSCSITUACAO VARCHAR(45), 
INSCPERIODO int, 
INSCPERCENTUALPC FLOAT, 
INSCPERCENTUALDO FLOAT,  
INSCDATAEXPEDICAO DATETIME, 
FOREIGN KEY (CODCURS) REFERENCES Curso(CODCURS), 
FOREIGN KEY (CPFALUNO) REFERENCES Aluno(CPFALUNO), 
PRIMARY KEY (INSCMATRICULA)
);
"""

CONTRATO = """CREATE TABLE [Contrato] ( 
CONTID  INT, 
INSCMATRICULA INT, 
CONTESTOB VARCHAR(3), 
CONTDATAINICIO DATETIME, 
CONTDATAFIM DATETIME, 
FOREIGN KEY (INSCMATRICULA) REFERENCES Inscrito(INSCMATRICULA),
PRIMARY KEY (CONTID) 
);
"""

SEGURO = """CREATE TABLE [Seguro] (  
SEGAPOLICE  INT, 
SEGACNPJ VARCHAR(45), 
SEGSTATUS VARCHAR(20), 
FOREIGN KEY (SEGACNPJ) REFERENCES Seguradora(SEGACNPJ),
Primary KEY (SEGAPOLICE) 
);
"""

ESTAGIO = """CREATE TABLE [Estagio] ( 
CONTID INT, 
CNPJCONCEDENTE  VARCHAR(45), 
CPFSUPERVISOR  VARCHAR(45), 
ORIENUMMATRICULA  INT, 
SEGAPOLICE INT, 
FOREIGN KEY (CONTID) REFERENCES Contrato(CONTID),
FOREIGN KEY (CNPJCONCEDENTE) REFERENCES Concedente(CNPJCONCEDENTE),
FOREIGN KEY (CPFSUPERVISOR) REFERENCES Supervisor(CPFSUPERVISOR),
FOREIGN KEY (ORIENUMMATRICULA) REFERENCES Orientador(ORIENUMMATRICULA),
FOREIGN KEY (SEGAPOLICE) REFERENCES Seguro(SEGAPOLICE)
);
"""

